# Generated by Django 4.1.3 on 2022-11-23 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pharmacy',
            new_name='Pharmacies',
        ),
    ]
