# Generated by Django 4.1.3 on 2022-11-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_pharmacy_pharmacies'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacies',
            name='accreditation_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pharmacies',
            name='city',
            field=models.CharField(default='toronto', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacies',
            name='fax',
            field=models.IntegerField(default=55555555),
        ),
        migrations.AddField(
            model_name='pharmacies',
            name='phone',
            field=models.IntegerField(default=5555555555),
        ),
        migrations.AddField(
            model_name='pharmacies',
            name='province',
            field=models.CharField(default='city', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacies',
            name='street',
            field=models.CharField(default='street', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacies',
            name='type',
            field=models.CharField(default='type', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='postal_code',
            field=models.CharField(max_length=6),
        ),
    ]
